version: '3.8'

services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices

  api-gateway:
    build: ./api-gateway
    ports:
      - "8765:8765"
    depends_on:
      - eureka-server
    networks:
      - microservices

  user-service:
    build: ./user-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    networks:
      - microservices

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - user-service
    networks:
      - microservices

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - microservices

  payment-service:
    build: ./payment-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - order-service
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
